# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "4.0.0-beta.4"
  license "MIT"

  depends_on "git" => :optional
  depends_on "oniguruma"
  depends_on "openssl@1.1"

  on_macos do
    url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.4/platform_4.0.0-beta.4_darwin_all.tar.gz"
    sha256 "010d1b75af7d84038e217985e81b8debd6002b106ae4be1f25f5ad1bf7f2e554"

    def install
      bin.install "platform"
      bash_completion.install "completion/bash/platform.bash" => "platform"
      zsh_completion.install "completion/zsh/_platform" => "_platform"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.4/platform_4.0.0-beta.4_linux_arm64.tar.gz"
      sha256 "80bbeb93ac1e6191a3017d8608afd759940562293276b7a4b91918bbb01d7700"

      def install
        bin.install "platform"
        bash_completion.install "completion/bash/platform.bash" => "platform"
        zsh_completion.install "completion/zsh/_platform" => "_platform"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.4/platform_4.0.0-beta.4_linux_amd64.tar.gz"
      sha256 "4d271900e9b1f5e0c1eac132900142e9884c7b3d38b2e6b72d18bc9801206ad6"

      def install
        bin.install "platform"
        bash_completion.install "completion/bash/platform.bash" => "platform"
        zsh_completion.install "completion/zsh/_platform" => "_platform"
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
