# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "4.0.0-beta.7"
  license "MIT"

  depends_on "git" => :optional
  depends_on "oniguruma"
  depends_on "openssl@1.1"

  on_macos do
    url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_darwin_all.tar.gz"
    sha256 "163d7dbebd6cd755b34d692b35e8582bfc97f7e6adf14d1c99f0793267c11402"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", "-s", shells: [:bash, :zsh])
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_linux_arm64.tar.gz"
      sha256 "ef0ae1d5c4934b7f6e0046fb24afec044223aa44c9174d0c959431d31bb9dc47"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", "-s", shells: [:bash, :zsh])
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_linux_amd64.tar.gz"
      sha256 "9869dc54f651c2ae5ca2c69973bd995eec109cba3d09e224b9d7664a8ba5dd33"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", "-s", shells: [:bash, :zsh])
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
