# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlatformshCli < Formula
  desc "Platform.sh CLI"
  homepage "https://docs.platform.sh/administration/cli.html"
  version "4.0.0-beta.7"
  license "MIT"

  depends_on "git" => :optional
  depends_on "oniguruma"
  depends_on "openssl@1.1"

  on_macos do
    url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_darwin_all.tar.gz"
    sha256 "3cf8816ad1b2f931983e926bd8c702967a94c30e88050026a0b25b9a5fa50d83"

    def install
      bin.install "platform"
      generate_completions_from_executable(bin/"platform", "completion", "-s")
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_linux_arm64.tar.gz"
      sha256 "2daab56eb1500707e77db5ca0a2ad9f308de625cd0cb9acf92671e5bc4d2ceed"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", "-s")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/akalipetis/psh-go/releases/download/4.0.0-beta.7/platform_4.0.0-beta.7_linux_amd64.tar.gz"
      sha256 "c0c21eef6d32dd638a5883deaf314a02ac132e49524f18f596a538cc8424cb27"

      def install
        bin.install "platform"
        generate_completions_from_executable(bin/"platform", "completion", "-s")
      end
    end
  end

  test do
    system "#{bin}/platform --version"
  end
end
